---
all:
  children:
    webservers:
      hosts:
        production:
          ansible_host: "{{ ansible_host }}"
          ansible_user: "{{ ansible_user }}"
          ansible_port: 22
          ansible_python_interpreter: /usr/bin/python3
          
  vars:
    app_name: tolus-ecommerce
    app_port: 3000
    app_user: www-data
    app_group: www-data
    deploy_dir: /var/www/tolus-ecommerce
    node_version: "20"
